
let editId=null;
function render(){const q=(search.value||'').toLowerCase(),f=filter.value,a=getData('assignments',[]).filter(x=>JSON.stringify(x).toLowerCase().includes(q)).filter(x=>!f||x.status===f);tableBody.innerHTML=a.length?a.map(x=>{const overdue=x.status!=='Completed'&&x.deadline<new Date().toISOString().slice(0,10);return `<tr><td><b>${esc(x.title)}</b></td><td>${esc(x.course)}</td><td>${fmtDate(x.deadline)} ${overdue?'<span class="badge danger">Overdue</span>':''}</td><td>${esc(x.priority)}</td><td><span class="badge ${x.status==='Completed'?'success':'warning'}">${esc(x.status)}</span></td><td><div class="actions"><button class="btn small success" onclick="toggleStatus('${x.id}')">${x.status==='Completed'?'Pending':'Complete'}</button>${rowActions(x.id,'openEdit','delItem')}</div></td></tr>`}).join(''):`<tr><td colspan="6"><div class="empty">No assignments.</div></td></tr>`}
function toggleStatus(id){const x=getData('assignments',[]).find(v=>v.id===id);updateData('assignments',id,{status:x.status==='Completed'?'Pending':'Completed'});notify('Status updated');render()}
function openEdit(id){const x=getData('assignments',[]).find(v=>v.id===id);editId=id;['title','course','description','deadline','priority','status'].forEach(k=>document.getElementById('f_'+k).value=x[k]??'');modalTitle.textContent='Edit Assignment';openModal('itemModal')}
function delItem(id){if(confirmDelete()){deleteData('assignments',id);notify('Deleted');render()}}
addBtn.onclick=()=>{editId=null;itemForm.reset();modalTitle.textContent='Add Assignment';openModal('itemModal')};
itemForm.onsubmit=e=>{e.preventDefault();const x={id:editId||uid(),title:f('title'),course:f('course'),description:f('description'),deadline:f('deadline'),priority:f('priority'),status:f('status')};editId?updateData('assignments',editId,x):addData('assignments',x);appNotification('Assignment saved');notify('Saved');closeModal('itemModal');render()};function f(k){return document.getElementById('f_'+k).value.trim()}
search.oninput=render;filter.onchange=render;document.addEventListener('DOMContentLoaded',render);
