
document.addEventListener('DOMContentLoaded',()=>{
 if(isLogged()){location.href='dashboard.html';return}
 document.querySelectorAll('[data-show-password]').forEach(b=>b.onclick=()=>{const i=document.getElementById(b.dataset.showPassword);i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'Show':'Hide'});
 const loginForm=document.getElementById('loginForm'),regForm=document.getElementById('registerForm'),showReg=document.getElementById('showRegister'),showLogin=document.getElementById('showLogin');
 showReg.onclick=()=>{loginForm.style.display='none';regForm.style.display='block';showReg.style.display='none';showLogin.style.display='inline'};
 showLogin.onclick=()=>{regForm.style.display='none';loginForm.style.display='block';showLogin.style.display='none';showReg.style.display='inline'};
 document.getElementById('forgot').onclick=e=>{e.preventDefault();const email=prompt('Enter your email:');if(email)alert('Demo mode: no email server is required. You can create/use the account locally.')};
 loginForm.onsubmit=e=>{e.preventDefault();const sid=loginForm.studentId.value.trim(),email=loginForm.email.value.trim(),password=loginForm.password.value;if(!sid||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!password){loginError.textContent='Enter a valid Student ID, email and password.';return}let users=getData('users',[]),u=users.find(x=>x.studentId===sid&&x.email.toLowerCase()===email.toLowerCase());if(!u){u={id:uid(),name:sid,studentId:sid,email,password};users.push(u);setData('users',users)}if(u.password!==password){loginError.textContent='Incorrect password.';return}setData('currentUser',u);if(!localStorage.getItem('profile'))setData('profile',{name:u.name,studentId:u.studentId,email:u.email,phone:'',department:'Software Engineering',program:'B.Sc. in Software Engineering',semester:'4th',section:'A',cgpa:'3.35',blood:'',address:'',about:'',picture:''});location.href='dashboard.html'};
 regForm.onsubmit=e=>{e.preventDefault();const name=regForm.name.value.trim(),sid=regForm.studentId.value.trim(),email=regForm.email.value.trim(),password=regForm.password.value;if(!name||!sid||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<4){regError.textContent='Fill all fields correctly.';return}let users=getData('users',[]);if(users.some(x=>x.studentId===sid||x.email.toLowerCase()===email.toLowerCase())){regError.textContent='Student ID or email already exists.';return}const u={id:uid(),name,studentId:sid,email,password};users.push(u);setData('users',users);setData('currentUser',u);setData('profile',{name,studentId:sid,email,phone:'',department:'',program:'',semester:'',section:'',cgpa:'',blood:'',address:'',about:'',picture:''});location.href='dashboard.html'};
});
