
const SC_KEYS=['users','currentUser','profile','courses','results','routine','assignments','events','notices','clubs','marketplace','lostFound','messages','notifications','settings'];
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function getData(k,f=[]){try{const v=localStorage.getItem(k);return v===null?f:JSON.parse(v)}catch{return f}}
function setData(k,v){localStorage.setItem(k,JSON.stringify(v))}
function addData(k,x){const a=getData(k,[]);a.push(x);setData(k,a);return x}
function updateData(k,id,c){const a=getData(k,[]).map(x=>x.id===id?{...x,...c}:x);setData(k,a);return a.find(x=>x.id===id)}
function deleteData(k,id){setData(k,getData(k,[]).filter(x=>x.id!==id))}
function currentUser(){return getData('currentUser',null)}function isLogged(){return !!currentUser()}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function fmtDate(d){return d?new Date(d+'T00:00:00').toLocaleDateString():'-'}
function notify(msg,type='success'){const box=document.querySelector('.toast-container')||document.body,t=document.createElement('div');t.className='toast '+type;t.textContent=msg;(document.querySelector('.toast-container')||document.body).appendChild(t);setTimeout(()=>t.remove(),2800)}
function appNotification(text,type='info'){const s=getData('settings',{notifications:true});if(s.notifications!==false)addData('notifications',{id:uid(),text,type,read:false,createdAt:new Date().toISOString()})}
function confirmDelete(msg='Are you sure you want to delete this item?'){return confirm(msg)}
function initData(){if(!localStorage.getItem('settings'))setData('settings',{theme:'light',notifications:true});if(!localStorage.getItem('courses'))setData('courses',[{id:uid(),code:'CSE101',name:'Structured Programming',credit:3,teacher:'Dr. Rahman',section:'A',semester:'Spring 2026',room:'B-201'},{id:uid(),code:'MAT102',name:'Mathematics-II',credit:3,teacher:'Ms. Sultana',section:'B',semester:'Spring 2026',room:'C-105'}]);if(!localStorage.getItem('results'))setData('results',[{id:uid(),code:'CSE101',name:'Structured Programming',credit:3,grade:'A',point:4},{id:uid(),code:'MAT102',name:'Mathematics-II',credit:3,grade:'B+',point:3.5}]);if(!localStorage.getItem('routine'))setData('routine',[{id:uid(),day:'Saturday',course:'CSE101',teacher:'Dr. Rahman',room:'B-201',start:'09:00',end:'10:30'}]);if(!localStorage.getItem('assignments'))setData('assignments',[{id:uid(),title:'Data Structure Lab Report',course:'CSE201',description:'Submit the lab report.',deadline:'2026-10-02',priority:'High',status:'Pending'}]);if(!localStorage.getItem('events'))setData('events',[{id:uid(),name:'Programming Contest',date:'2026-10-10',time:'10:00',location:'Auditorium',organizer:'CPC',description:'Campus programming contest.',registered:false}]);if(!localStorage.getItem('notices'))setData('notices',[{id:uid(),title:'Midterm Examination Notice',description:'Check the department notice board for details.',date:'2026-09-25',category:'Exam',author:'Department Office'}]);if(!localStorage.getItem('clubs'))setData('clubs',[{id:uid(),name:'Programming Club',description:'Programming and problem solving community.',president:'Club President',email:'club@example.com',members:25,category:'Technology',joined:false},{id:uid(),name:'Robotics Club',description:'Robotics and embedded systems.',president:'Club President',email:'robotics@example.com',members:18,category:'Technology',joined:false},{id:uid(),name:'Data Science Club',description:'Data analysis, ML and AI.',president:'Club President',email:'data@example.com',members:20,category:'Technology',joined:false}]);if(!localStorage.getItem('marketplace'))setData('marketplace',[]);if(!localStorage.getItem('lostFound'))setData('lostFound',[]);if(!localStorage.getItem('messages'))setData('messages',[]);if(!localStorage.getItem('notifications'))setData('notifications',[])}
initData();
